tap 'homebrew/bundle'
tap 'hashicorp/tap'

brew 'mas'
brew 'ack'
brew 'coreutils'
brew 'openssl'
brew 'wget'
brew 'git'
brew 'htop'
brew 'tig'
# brew 'fasd'
brew 'jq'
brew 'tmux'
brew 'tree'
brew 'hashicorp/tap/terraform'
brew 'fzf'
brew 'awscli'
brew 'ripgrep'
brew 'vim'
brew 'pipx'

cask '1password'
cask 'alfred'
cask 'google-chrome'
cask 'slack'
cask 'iterm2'
cask 'karabiner-elements'
cask 'visual-studio-code'
cask 'clipy'
cask 'jetbrains-toolbox'
cask 'joplin'
cask 'lens'
cask 'rectangle'
cask 'logitech-options'
cask 'rancher'
cask 'notion'

mas 'runcat', id:1429033973
